version: 2

before:
  hooks:
    - go mod download

builds:
  - id: stepanel
    main: ./cmd/stepanel
    binary: stepanel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/cyberducttape/StePanel.Commit={{ .FullCommit }} -X github.com/cyberducttape/StePanel.BuildDate={{ .Date }}
  - id: stepanel-root
    main: ./cmd/stepanel-root
    binary: stepanel-root
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: stepanel
    ids:
      - stepanel
      - stepanel-root
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - SECURITY.md
      - install.sh
      - deploy/**
      - web/**

checksum:
  name_template: SHA256SUMS
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
