package main

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

var gitRefPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._/@+-]{0,127}$`)
var gitCommitPattern = regexp.MustCompile(`^[0-9a-f]{40}$`)

// WebhookReplayCache prevents replay attacks on webhook deliveries
type WebhookReplayCache struct {
	mu     sync.RWMutex
	cache  map[string]time.Time // deliveryID -> timestamp
	maxAge time.Duration
}

// NewWebhookReplayCache creates a cache with bounded lifetime
func NewWebhookReplayCache(maxAge time.Duration) *WebhookReplayCache {
	rc := &WebhookReplayCache{
		cache:  make(map[string]time.Time),
		maxAge: maxAge,
	}
	// Periodically clean up old entries
	go rc.cleanupLoop()
	return rc
}

// Check verifies if deliveryID has been seen before and is within the time window
func (rc *WebhookReplayCache) Check(deliveryID string, timestamp time.Time) bool {
	rc.mu.RLock()
	defer rc.mu.RUnlock()

	if _, exists := rc.cache[deliveryID]; exists {
		// Duplicate delivery (already seen)
		return false
	}

	// Check if timestamp is too old (stale)
	if time.Since(timestamp) > rc.maxAge {
		return false
	}

	return true
}

// Store records a new delivery ID with its timestamp
func (rc *WebhookReplayCache) Store(deliveryID string, timestamp time.Time) {
	rc.mu.Lock()
	defer rc.mu.Unlock()
	rc.cache[deliveryID] = timestamp

	// Prune if cache exceeds 10K entries
	if len(rc.cache) > 10000 {
		rc.pruneOldEntriesLocked()
	}
}

// pruneOldEntriesLocked removes entries older than maxAge
func (rc *WebhookReplayCache) pruneOldEntriesLocked() {
	now := time.Now()
	for id, ts := range rc.cache {
		if now.Sub(ts) > rc.maxAge {
			delete(rc.cache, id)
		}
	}
}

// cleanupLoop periodically cleans up old entries
func (rc *WebhookReplayCache) cleanupLoop() {
	ticker := time.NewTicker(5 * time.Minute)
	defer ticker.Stop()
	for range ticker.C {
		rc.mu.Lock()
		rc.pruneOldEntriesLocked()
		rc.mu.Unlock()
	}
}

type gitDeployRequest struct {
	Site       string `json:"site"`
	Repository string `json:"repository"`
	Ref        string `json:"ref"`
}

// gitRepository is deliberately narrower than Git's general URL syntax.  HTTPS
// remains available for public sources; SSH is available only as git@host:path
// and only after a per-site deploy key has been generated by the privileged
// helper.  Personal tokens, passwords, query strings, and arbitrary SSH users
// are never accepted.
type gitRepository struct {
	URL     string
	Host    string
	Private bool
}

var gitSSHRepositoryPattern = regexp.MustCompile(`^git@([A-Za-z0-9.-]+):([A-Za-z0-9._/-]+\.git)$`)

func parseGitRepository(raw, allowedHosts string) (gitRepository, error) {
	raw = strings.TrimSpace(raw)
	if match := gitSSHRepositoryPattern.FindStringSubmatch(raw); match != nil {
		if !gitHostAllowed(allowedHosts, strings.ToLower(match[1])) {
			return gitRepository{}, errors.New("repository host is not in STEPANEL_GIT_ALLOWED_HOSTS")
		}
		return gitRepository{URL: raw, Host: strings.ToLower(match[1]), Private: true}, nil
	}
	repository, err := url.Parse(raw)
	if err != nil || repository.Scheme != "https" || repository.User != nil || repository.Host == "" || repository.Port() != "" || repository.RawQuery != "" || repository.Fragment != "" || strings.ContainsAny(raw, "\x00\r\n") || !strings.HasSuffix(strings.ToLower(repository.Path), ".git") {
		return gitRepository{}, errors.New("repository must be an HTTPS .git URL without credentials or an SSH git@host:path.git URL")
	}
	if !gitHostAllowed(allowedHosts, repository.Hostname()) {
		return gitRepository{}, errors.New("repository host is not in STEPANEL_GIT_ALLOWED_HOSTS")
	}
	return gitRepository{URL: raw, Host: strings.ToLower(repository.Hostname())}, nil
}

type gitDeployResult struct {
	DeploymentID string `json:"deployment_id,omitempty"`
	Site         string `json:"site"`
	Repository   string `json:"repository"`
	Ref          string `json:"ref"`
	Commit       string `json:"commit"`
	Previous     string `json:"previous_release,omitempty"`
}

type gitRollbackRequest struct {
	Site    string `json:"site"`
	Confirm string `json:"confirm"`
}

// gitWebhookSiteKey carries the authenticated site name for a request that
// passed webhook signature verification. The site is derived from the URL
// path (/api/sites/git-webhook/:site) and validated against that site's
// per-site HMAC secret, so an authenticated webhook proves authority over
// exactly one site and no other. gitDeploy uses the value in this key —
// never input.Site from the body — as the trusted deploy target when the
// request came in via the webhook path.
type gitWebhookSiteKey struct{}

// webhookAuthenticatedSite returns the authenticated site name if the
// request came in through the webhook path and passed signature
// verification, or "" otherwise.
func webhookAuthenticatedSite(r *http.Request) string {
	site, _ := r.Context().Value(gitWebhookSiteKey{}).(string)
	return site
}

// GitWebhookConfig stores per-site webhook configuration.
// Each site can have its own webhook secret, allowed repositories, and allowed refs.
// This prevents a single leaked secret from compromising all sites.
type GitWebhookConfig struct {
	Site          string    `json:"site"`
	Repositories  []string  `json:"repositories"` // allowed repository URLs
	AllowedRefs   []string  `json:"allowed_refs"` // allowed Git refs (branches/tags)
	WebhookSecret string    `json:"webhook_secret"`
	EnabledAt     time.Time `json:"enabled_at"`
	LastWebhookAt time.Time `json:"last_webhook_at,omitempty"`
}

// gitWebhookSitePath extracts site from webhook URL: /api/sites/git-webhook/:site
func gitWebhookSitePath(path string) string {
	// Path format: /api/sites/git-webhook/:site
	prefix := "/api/sites/git-webhook/"
	if !strings.HasPrefix(path, prefix) {
		return ""
	}
	site := strings.TrimPrefix(path, prefix)
	// Remove any trailing slashes or query parameters
	if idx := strings.IndexAny(site, "/?"); idx >= 0 {
		site = site[:idx]
	}
	return site
}

// verifyWebhookSignature verifies HMAC-SHA256 signature using per-site webhook secret
func verifyWebhookSignature(body []byte, signature string, webhookSecret string) bool {
	provided, err := hex.DecodeString(strings.TrimSpace(strings.TrimPrefix(signature, "sha256=")))
	if err != nil {
		return false
	}
	digest := hmac.New(sha256.New, []byte(webhookSecret))
	_, _ = digest.Write(body)
	return hmac.Equal(provided, digest.Sum(nil))
}

// verifyWebhookTimestamp checks if the timestamp is recent (prevents stale/old replays)
func verifyWebhookTimestamp(timestamp string, maxAge time.Duration) (time.Time, error) {
	ts, err := time.Parse(time.RFC3339, timestamp)
	if err != nil {
		return time.Time{}, err
	}
	if time.Since(ts) > maxAge {
		return time.Time{}, errors.New("webhook timestamp too old")
	}
	return ts, nil
}

// matchRefPattern reports whether the Git ref ref is authorized by any of
// the configured patterns. Matching is anchored (whole-ref) and
// case-sensitive, mirroring Git's own ref semantics on case-sensitive
// filesystems.
//
// Supported pattern forms:
//
//   - Exact ref:  "refs/heads/main"
//   - Glob:       "refs/heads/release/*"  (path.Match: '*' does not cross '/')
//   - Recursive:  "refs/heads/release/**" (matches "refs/heads/release" and
//     everything nested underneath it)
//   - Bare branch/tag shorthand: "main", "release/*", "v1.*" — matched
//     against ref stripped of a "refs/heads/" or "refs/tags/" prefix. Kept
//     for backward compatibility with configs that pre-date full-ref
//     patterns; new patterns should be written in full-ref form.
//
// This replaces the previous implementation which stripped '*' from the
// pattern and did a substring match, so "refs/heads/release/*" effectively
// authorized any ref containing the substring "refs/heads/release/" —
// including unrelated branches like "refs/heads/other-release/main".
func matchRefPattern(ref string, patterns []string) bool {
	ref = strings.TrimSpace(ref)
	if ref == "" {
		return false
	}
	shortHead, shortHeadOK := "", false
	shortTag, shortTagOK := "", false
	if strings.HasPrefix(ref, "refs/heads/") {
		shortHead = strings.TrimPrefix(ref, "refs/heads/")
		shortHeadOK = shortHead != ""
	}
	if strings.HasPrefix(ref, "refs/tags/") {
		shortTag = strings.TrimPrefix(ref, "refs/tags/")
		shortTagOK = shortTag != ""
	}
	for _, pattern := range patterns {
		pattern = strings.TrimSpace(pattern)
		if pattern == "" {
			continue
		}
		if refMatchesPattern(ref, pattern) {
			return true
		}
		// Backward-compat: a bare pattern (no "refs/..." prefix) matches
		// against the short ref name. This lets a config that says just
		// "main" authorize a ref of "refs/heads/main".
		if strings.HasPrefix(pattern, "refs/") {
			continue
		}
		if shortHeadOK && refMatchesPattern(shortHead, pattern) {
			return true
		}
		if shortTagOK && refMatchesPattern(shortTag, pattern) {
			return true
		}
	}
	return false
}

// refMatchesPattern is the single-pattern anchored-glob primitive.
//   - '**' as a suffix matches the base and every descendant.
//   - Otherwise path.Match is used: '*' does not cross '/', '?' matches one
//     non-'/' rune, character classes are supported.
//   - A pattern with no glob metacharacters is treated as an exact match.
func refMatchesPattern(ref, pattern string) bool {
	if pattern == ref {
		return true
	}
	if strings.HasSuffix(pattern, "/**") {
		prefix := strings.TrimSuffix(pattern, "/**")
		return ref == prefix || strings.HasPrefix(ref, prefix+"/")
	}
	if !strings.ContainsAny(pattern, "*?[") {
		return false
	}
	matched, err := path.Match(pattern, ref)
	return err == nil && matched
}

func (a *App) gitWebhook(w http.ResponseWriter, r *http.Request) {
	site := gitWebhookSitePath(r.URL.Path)
	if site == "" {
		http.Error(w, "site name required in webhook URL path", http.StatusBadRequest)
		return
	}
	site = safeUser(site)

	body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, 16<<10))
	if err != nil {
		http.Error(w, "invalid webhook body", 400)
		return
	}

	var webhookSecret string

	if a.Webhooks != nil {
		config, err := a.Webhooks.GetWebhookConfig(site)
		if err != nil {
			http.Error(w, "webhook configuration error", http.StatusInternalServerError)
			_ = Audit(a.Config.AuditLog, "webhook.auth.error", site, fmt.Sprintf("get webhook config: %v", err))
			return
		}
		if config != nil {
			webhookSecret = config.WebhookSecret
		}
	}

	if webhookSecret == "" {
		if a.Config.GitWebhookSecret == "" {
			http.Error(w, "webhook not configured for this site", http.StatusNotFound)
			return
		}
		webhookSecret = a.Config.GitWebhookSecret
	}

	signature := r.Header.Get("X-StePanel-Signature")
	if !verifyWebhookSignature(body, signature, webhookSecret) {
		http.Error(w, "invalid webhook signature", http.StatusUnauthorized)
		_ = Audit(a.Config.AuditLog, "webhook.auth.failed", site, "invalid signature")
		return
	}

	// Replay protection: verify timestamp is recent and delivery ID hasn't been seen
	deliveryID := r.Header.Get("X-StePanel-Delivery-ID")
	timestamp := r.Header.Get("X-StePanel-Delivery-Timestamp")
	if deliveryID == "" || timestamp == "" {
		http.Error(w, "missing delivery ID or timestamp", 400)
		return
	}

	ts, err := verifyWebhookTimestamp(timestamp, 5*time.Minute)
	if err != nil {
		http.Error(w, "invalid or stale webhook timestamp", 400)
		return
	}

	if !a.webhookReplayCache.Check(deliveryID, ts) {
		http.Error(w, "duplicate or stale webhook delivery", 409)
		return
	}

	a.webhookReplayCache.Store(deliveryID, ts)

	// Carry the site the signature actually authorized into gitDeploy's context.
	// gitDeploy treats that value — not input.Site from the body — as the
	// trusted deploy target, so a valid signature for siteA can never trigger a
	// deploy on siteB regardless of what the body claims.
	request := r.Clone(context.WithValue(r.Context(), gitWebhookSiteKey{}, site))
	request.Body = io.NopCloser(bytes.NewReader(body))
	a.gitDeploy(w, request)
}

// containsString checks if a string is in a list (case-insensitive for URLs)
func containsString(list []string, value string) bool {
	valueLower := strings.ToLower(value)
	for _, item := range list {
		if strings.ToLower(item) == valueLower {
			return true
		}
	}
	return false
}

// sanitizeGitError returns a customer-safe error message without leaking infrastructure details
func sanitizeGitError(output string) string {
	output = strings.ToLower(output)
	switch {
	case strings.Contains(output, "repository not found"):
		return "Repository not found. Check your repository URL."
	case strings.Contains(output, "permission denied"), strings.Contains(output, "authentication failed"):
		return "Authentication failed. Check your repository credentials."
	case strings.Contains(output, "could not read"):
		return "Could not read repository. Check your credentials and try again."
	case strings.Contains(output, "not a git repository"):
		return "Invalid Git repository. Check your repository URL."
	case strings.Contains(output, "timed out"), strings.Contains(output, "connection timeout"):
		return "Repository connection timed out. The server may be temporarily unavailable."
	case strings.Contains(output, "connection refused"):
		return "Could not connect to repository server. Check that the repository is accessible."
	case strings.Contains(output, "no such file"):
		return "Repository or branch not found."
	default:
		return "Git operation failed. Please check your repository details and try again."
	}
}

// gitDeploy intentionally does not evaluate repository-provided build scripts.
// Build execution belongs in a separately sandboxed runner.
//
// SECURITY: Webhook requests bypass CSRF and per-site HTTP-auth checks because
// the webhook signature verification already binds the request to a specific
// site (the one whose per-site HMAC secret validated the body). That binding
// is only meaningful if the deploy actually targets *that* site — so when a
// webhook-authenticated site is present in the context we treat it as the
// only trusted deploy target and refuse any body claim that disagrees.
func (a *App) gitDeploy(w http.ResponseWriter, r *http.Request) {
	webhookSite := webhookAuthenticatedSite(r)
	isWebhook := webhookSite != ""
	if r.Method != http.MethodPost || (!a.Auth.CSRF(r) && !isWebhook) {
		http.Error(w, "invalid request", http.StatusForbidden)
		return
	}
	var input gitDeployRequest
	if err := decodeJSON(w, r, 16<<10, &input); err != nil {
		http.Error(w, "invalid JSON", http.StatusBadRequest)
		return
	}
	input.Site = safeUser(input.Site)
	input.Repository = strings.TrimSpace(input.Repository)
	input.Ref = strings.TrimSpace(input.Ref)
	if input.Ref == "" {
		input.Ref = "main"
	}
	if isWebhook {
		// The signature only proved authority over webhookSite. Any body value
		// that disagrees is a cross-site attempt: 403, audited. An absent body
		// site is fine — we substitute the authenticated one — so payload
		// formats that omit "site" continue to work.
		if input.Site != "" && input.Site != webhookSite {
			_ = Audit(a.Config.AuditLog, "webhook.site.mismatch", webhookSite, fmt.Sprintf("body claimed site %q", input.Site))
			http.Error(w, "webhook body targets a different site than the URL signature authorized", http.StatusForbidden)
			return
		}
		input.Site = webhookSite
	}
	if input.Site == "" || !gitRefPattern.MatchString(input.Ref) {
		http.Error(w, "invalid site or Git ref", http.StatusUnprocessableEntity)
		return
	}
	if !isWebhook {
		if _, ok := a.requireSiteAccess(w, r, input.Site, "site is not assigned to this account", http.StatusForbidden); !ok {
			return
		}
	}
	if !isWebhook && !a.Auth.HasRequiredCustomerScope(r, "deploy:write") {
		http.Error(w, "API token lacks the deploy:write scope", http.StatusForbidden)
		return
	}

	if isWebhook && a.Webhooks != nil {
		config, err := a.Webhooks.GetWebhookConfig(input.Site)
		if err == nil && config != nil {
			repoLower := strings.ToLower(strings.TrimSpace(input.Repository))
			if len(config.Repositories) > 0 && !containsString(config.Repositories, repoLower) {
				http.Error(w, "repository is not authorized for this webhook", http.StatusForbidden)
				_ = Audit(a.Config.AuditLog, "webhook.deploy.unauthorized", input.Site, fmt.Sprintf("repository not in whitelist: %s", input.Repository))
				return
			}
			if len(config.AllowedRefs) > 0 && !matchRefPattern(input.Ref, config.AllowedRefs) {
				http.Error(w, "ref is not authorized for this webhook", http.StatusForbidden)
				_ = Audit(a.Config.AuditLog, "webhook.deploy.unauthorized", input.Site, fmt.Sprintf("ref not in whitelist: %s", input.Ref))
				return
			}
		}
	}
	releaseUnlock := a.siteOperations.Acquire(input.Site)
	defer releaseUnlock()
	repository, err := parseGitRepository(input.Repository, a.Config.GitAllowedHosts)
	if err != nil {
		http.Error(w, err.Error(), http.StatusUnprocessableEntity)
		return
	}
	publicRoot := filepath.Join(a.Config.WebRoot, "sites", input.Site, "public")
	if err := ensureInside(a.Config.WebRoot, publicRoot); err != nil {
		http.Error(w, err.Error(), http.StatusUnprocessableEntity)
		return
	}
	siteRoot := filepath.Dir(publicRoot)
	if info, err := os.Stat(siteRoot); err != nil || !info.IsDir() {
		http.Error(w, "site root does not exist", http.StatusUnprocessableEntity)
		return
	}
	gitPath, err := exec.LookPath("git")
	if err != nil {
		http.Error(w, "Git is not installed", http.StatusServiceUnavailable)
		return
	}
	release := filepath.Join(siteRoot, ".stepanel-release-"+strings.ReplaceAll(newRequestID(), "-", ""))
	if err := os.Mkdir(release, 0700); err != nil {
		http.Error(w, "unable to create release staging directory", http.StatusInternalServerError)
		return
	}
	defer os.RemoveAll(release)
	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Minute)
	defer cancel()
	var cloneOutput []byte
	if repository.Private {
		cloneOutput, err = runBoundedCommand(ctx, helperCommandContext(ctx, a.Config, a.Config.GitCtl, "clone", input.Site, repository.URL, input.Ref, release, a.Config.GitAllowedHosts))
	} else {
		clone := exec.CommandContext(ctx, gitPath, "-c", "credential.helper=", "clone", "--depth", "1", "--branch", input.Ref, "--single-branch", "--no-tags", repository.URL, release)
		clone.Env = append(os.Environ(), "GIT_TERMINAL_PROMPT=0", "GIT_ASKPASS=/bin/false", "GIT_CONFIG_NOSYSTEM=1", "GIT_CONFIG_GLOBAL=/dev/null")
		cloneOutput, err = runBoundedCommand(ctx, clone)
	}
	if err != nil {
		log.Printf("Git clone failed for site %s (repo %s): %v\nOutput: %s", input.Site, input.Repository, err, strings.TrimSpace(string(cloneOutput)))
		http.Error(w, sanitizeGitError(string(cloneOutput)), http.StatusBadGateway)
		return
	}
	commitOutput, err := runBoundedCommand(ctx, exec.CommandContext(ctx, gitPath, "-C", release, "rev-parse", "HEAD"))
	if err != nil {
		http.Error(w, "unable to identify checked-out commit", http.StatusBadGateway)
		return
	}
	commit := strings.TrimSpace(string(commitOutput))
	if !gitCommitPattern.MatchString(commit) {
		http.Error(w, "Git returned an invalid commit identifier", http.StatusBadGateway)
		return
	}
	if err := validateGitRelease(release, a.Config.MaxEntries); err != nil {
		http.Error(w, "repository contains an unsafe release tree: "+err.Error(), http.StatusUnprocessableEntity)
		return
	}
	if err := os.RemoveAll(filepath.Join(release, ".git")); err != nil {
		http.Error(w, "unable to remove Git metadata from release", http.StatusInternalServerError)
		return
	}
	a.gitActivationMu.Lock()
	defer a.gitActivationMu.Unlock()
	previous := ""
	if _, err := os.Stat(publicRoot); err == nil {
		previous = filepath.Join(siteRoot, ".stepanel-previous-"+strings.ReplaceAll(newRequestID(), "-", ""))
		if err := os.Rename(publicRoot, previous); err != nil {
			http.Error(w, "unable to preserve the current release", http.StatusInternalServerError)
			return
		}
	}
	if err := os.Rename(release, publicRoot); err != nil {
		if previous != "" {
			if rollbackErr := os.Rename(previous, publicRoot); rollbackErr != nil {
				http.Error(w, "unable to activate the new release; rollback failed: "+rollbackErr.Error(), http.StatusServiceUnavailable)
				return
			}
		}
		http.Error(w, "unable to activate the new release", http.StatusInternalServerError)
		return
	}
	if err := siteHelper(a.Config, "seal", input.Site); err != nil {
		if rollbackErr := rollbackGitActivation(publicRoot, previous); rollbackErr != nil {
			http.Error(w, "site isolation failed and release rollback failed: "+rollbackErr.Error(), http.StatusServiceUnavailable)
			return
		}
		http.Error(w, "site isolation could not be restored", http.StatusServiceUnavailable)
		return
	}
	result := gitDeployResult{Site: input.Site, Repository: input.Repository, Ref: input.Ref, Commit: commit, Previous: previous}
	if err := pruneGitReleasesWithPolicy(siteRoot, a.Config.GitReleaseRetention, time.Duration(a.Config.GitReleaseMaxAgeHours)*time.Hour, a.Config.GitReleaseMaxBytes); err != nil {
		log.Printf("Git release retention for %s: %v", input.Site, err)
	}
	a.recordDeployment(input.Site, "activation", "completed", "atomic Git release activated", result, "")
	if err := AuditAs(a.Config.AuditLog, a.Auth.UsernameForRequest(r), "site.git-deployed", input.Site, input.Repository+"@"+commit); err != nil {
		log.Printf("Git release activated but audit persistence is unavailable: %v", err)
	}
	writeJSON(w, http.StatusAccepted, result)
}

func rollbackGitActivation(publicRoot, previous string) error {
	if err := os.RemoveAll(publicRoot); err != nil {
		return fmt.Errorf("remove failed release: %w", err)
	}
	if previous != "" {
		if err := os.Rename(previous, publicRoot); err != nil {
			return fmt.Errorf("restore previous release: %w", err)
		}
	}
	return nil
}

func (a *App) gitRollback(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost || !a.Auth.CSRF(r) {
		http.Error(w, "invalid request", http.StatusForbidden)
		return
	}
	var input gitRollbackRequest
	if err := decodeJSON(w, r, 4096, &input); err != nil {
		http.Error(w, "invalid JSON", http.StatusBadRequest)
		return
	}
	input.Site = safeUser(input.Site)
	if input.Site == "" || input.Confirm != "ROLLBACK "+input.Site {
		http.Error(w, "confirmation must exactly match ROLLBACK <site>", http.StatusUnprocessableEntity)
		return
	}
	siteRoot := filepath.Join(a.Config.WebRoot, "sites", input.Site)
	publicRoot := filepath.Join(siteRoot, "public")
	if err := ensureInside(a.Config.WebRoot, publicRoot); err != nil {
		http.Error(w, "invalid site root", http.StatusUnprocessableEntity)
		return
	}
	releaseUnlock := a.siteOperations.Acquire(input.Site)
	defer releaseUnlock()
	a.gitActivationMu.Lock()
	defer a.gitActivationMu.Unlock()
	previous, err := latestPreviousRelease(siteRoot)
	if err != nil {
		http.Error(w, "no previous Git release is available", http.StatusConflict)
		return
	}
	if err := validateGitRelease(previous, a.Config.MaxEntries); err != nil {
		http.Error(w, "previous release failed safety validation", http.StatusConflict)
		return
	}
	if info, err := os.Stat(publicRoot); err != nil || !info.IsDir() {
		http.Error(w, "active site release is unavailable", http.StatusConflict)
		return
	}
	replaced := filepath.Join(siteRoot, ".stepanel-previous-"+strings.ReplaceAll(newRequestID(), "-", ""))
	if err := os.Rename(publicRoot, replaced); err != nil {
		http.Error(w, "unable to preserve the active release", http.StatusInternalServerError)
		return
	}
	if err := os.Rename(previous, publicRoot); err != nil {
		_ = os.Rename(replaced, publicRoot)
		http.Error(w, "unable to activate the previous release", http.StatusInternalServerError)
		return
	}
	if err := siteHelper(a.Config, "seal", input.Site); err != nil {
		_ = os.Rename(publicRoot, previous)
		_ = os.Rename(replaced, publicRoot)
		http.Error(w, "rollback could not restore site isolation", http.StatusServiceUnavailable)
		return
	}
	if err := AuditAs(a.Config.AuditLog, a.Auth.Username, "site.git-rolled-back", input.Site, filepath.Base(previous)); err != nil {
		log.Printf("Git rollback completed but audit persistence is unavailable: %v", err)
	}
	if err := pruneGitReleasesWithPolicy(siteRoot, a.Config.GitReleaseRetention, time.Duration(a.Config.GitReleaseMaxAgeHours)*time.Hour, a.Config.GitReleaseMaxBytes); err != nil {
		log.Printf("Git release retention for %s: %v", input.Site, err)
	}
	writeJSON(w, http.StatusOK, map[string]string{"site": input.Site, "activated": filepath.Base(previous), "replaced_release": filepath.Base(replaced)})
}

func pruneGitReleases(siteRoot string, retain int) error {
	return pruneGitReleasesWithPolicy(siteRoot, retain, 0, 0)
}

func pruneGitReleasesWithPolicy(siteRoot string, retain int, maxAge time.Duration, maxBytes int64) error {
	if retain < 1 {
		return errors.New("release retention must preserve at least one rollback release")
	}
	entries, err := os.ReadDir(siteRoot)
	if err != nil {
		return err
	}
	type candidate struct {
		path     string
		modified time.Time
		bytes    int64
	}
	items := []candidate{}
	for _, entry := range entries {
		if !entry.IsDir() || entry.Type()&os.ModeSymlink != 0 || !strings.HasPrefix(entry.Name(), ".stepanel-previous-") {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		releasePath, err := safePath(siteRoot, entry.Name())
		if err != nil {
			return err
		}
		size, err := gitReleaseSize(releasePath)
		if err != nil {
			return err
		}
		items = append(items, candidate{releasePath, info.ModTime(), size})
	}
	sort.Slice(items, func(i, j int) bool { return items[i].modified.After(items[j].modified) })
	if len(items) == 0 {
		return nil
	}
	remove := make(map[string]bool)
	for i, item := range items {
		// The newest previous tree is the immediate rollback target and is
		// never removed, even when it exceeds age or storage policy.
		if i == 0 {
			continue
		}
		if i >= retain || maxAge > 0 && time.Since(item.modified) > maxAge {
			remove[item.path] = true
		}
	}
	if maxBytes > 0 {
		var total int64
		for _, item := range items {
			total += item.bytes
		}
		for i := len(items) - 1; i > 0 && total > maxBytes; i-- {
			if !remove[items[i].path] {
				remove[items[i].path] = true
			}
			total -= items[i].bytes
		}
	}
	for _, item := range items {
		if !remove[item.path] {
			continue
		}
		if err := validateGitRelease(item.path, 1000000); err != nil {
			return fmt.Errorf("refuse to prune invalid release: %w", err)
		}
		if err := os.RemoveAll(item.path); err != nil {
			return err
		}
	}
	return nil
}

func gitReleaseSize(root string) (int64, error) {
	var total int64
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return filepath.SkipDir
		}
		if info.Mode().IsRegular() {
			if info.Size() < 0 || total > (1<<63-1)-info.Size() {
				return errors.New("Git release size overflow")
			}
			total += info.Size()
		}
		return nil
	})
	return total, err
}

func pruneAllGitReleases(cfg Config) error {
	root := filepath.Join(cfg.WebRoot, "sites")
	entries, err := os.ReadDir(root)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if !entry.IsDir() || safeUser(entry.Name()) == "" {
			continue
		}
		if err := pruneGitReleasesWithPolicy(filepath.Join(root, entry.Name()), cfg.GitReleaseRetention, time.Duration(cfg.GitReleaseMaxAgeHours)*time.Hour, cfg.GitReleaseMaxBytes); err != nil {
			return fmt.Errorf("%s: %w", entry.Name(), err)
		}
	}
	return nil
}

func latestPreviousRelease(siteRoot string) (string, error) {
	entries, err := os.ReadDir(siteRoot)
	if err != nil {
		return "", err
	}
	type candidate struct {
		path string
		time time.Time
	}
	var latest candidate
	for _, entry := range entries {
		if !entry.IsDir() || entry.Type()&os.ModeSymlink != 0 || !strings.HasPrefix(entry.Name(), ".stepanel-previous-") {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			continue
		}
		if latest.path == "" || info.ModTime().After(latest.time) || info.ModTime().Equal(latest.time) && entry.Name() > filepath.Base(latest.path) {
			latest = candidate{path: filepath.Join(siteRoot, entry.Name()), time: info.ModTime()}
		}
	}
	if latest.path == "" {
		return "", errors.New("no previous release")
	}
	return latest.path, nil
}

func validateGitAllowedHosts(value string) error {
	if strings.TrimSpace(value) == "" {
		return errors.New("STEPANEL_GIT_ALLOWED_HOSTS must contain at least one hostname")
	}
	for _, host := range strings.Split(value, ",") {
		host = strings.TrimSpace(strings.ToLower(host))
		if host == "" || strings.ContainsAny(host, "\x00\r\n:/") || net.ParseIP(host) != nil || !domainPattern.MatchString(host) {
			return fmt.Errorf("STEPANEL_GIT_ALLOWED_HOSTS contains invalid hostname %q", host)
		}
	}
	return nil
}

func gitHostAllowed(allowed, host string) bool {
	host = strings.ToLower(strings.TrimSuffix(host, "."))
	for _, candidate := range strings.Split(allowed, ",") {
		if host == strings.TrimSpace(strings.ToLower(candidate)) {
			return true
		}
	}
	return false
}

func validateGitRelease(root string, maxEntries int) error {
	if maxEntries < 1 {
		maxEntries = 100000
	}
	entries := 0
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		entries++
		if entries > maxEntries {
			return errors.New("release exceeds the configured entry limit")
		}
		if path == root || strings.HasPrefix(path, filepath.Join(root, ".git")+string(os.PathSeparator)) || path == filepath.Join(root, ".git") {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		if entry.Type()&os.ModeSymlink != 0 || !entry.IsDir() && !info.Mode().IsRegular() {
			return fmt.Errorf("%s is not a regular file or directory", filepath.Base(path))
		}
		return nil
	})
}

func newRequestID() string {
	id, err := randomSecret()
	if err != nil {
		return time.Now().UTC().Format("20060102150405.000000000")
	}
	return id
}

// WebhookConfigStore manages per-site webhook configuration in the control-plane database
type WebhookConfigStore struct {
	mu sync.RWMutex
	db *sql.DB
}

// NewWebhookConfigStore creates a webhook configuration manager
func NewWebhookConfigStore(database *sql.DB) *WebhookConfigStore {
	return &WebhookConfigStore{db: database}
}

// InitializeSchema creates the webhook configuration tables
func (wcs *WebhookConfigStore) InitializeSchema() error {
	schema := `
	CREATE TABLE IF NOT EXISTS webhook_configs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		site TEXT NOT NULL UNIQUE,
		webhook_secret TEXT NOT NULL,
		enabled BOOLEAN DEFAULT 1,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	);

	CREATE TABLE IF NOT EXISTS webhook_allowed_repos (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		webhook_id INTEGER NOT NULL,
		repository_url TEXT NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (webhook_id) REFERENCES webhook_configs(id) ON DELETE CASCADE,
		UNIQUE(webhook_id, repository_url)
	);

	CREATE TABLE IF NOT EXISTS webhook_allowed_refs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		webhook_id INTEGER NOT NULL,
		ref_pattern TEXT NOT NULL,
		pattern_type TEXT DEFAULT 'glob',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (webhook_id) REFERENCES webhook_configs(id) ON DELETE CASCADE,
		UNIQUE(webhook_id, ref_pattern)
	);

	CREATE INDEX IF NOT EXISTS idx_webhook_site ON webhook_configs(site);
	`

	_, err := wcs.db.Exec(schema)
	return err
}

// SetWebhookConfig creates or updates a webhook configuration for a site
func (wcs *WebhookConfigStore) SetWebhookConfig(site, secret string, repos, refPatterns []string) error {
	wcs.mu.Lock()
	defer wcs.mu.Unlock()

	tx, err := wcs.db.BeginTx(context.Background(), nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	var id int64
	err = tx.QueryRow("SELECT id FROM webhook_configs WHERE site = ?", site).Scan(&id)
	if err != nil && err != sql.ErrNoRows {
		return err
	}

	if err == sql.ErrNoRows {
		result, err := tx.Exec(
			"INSERT INTO webhook_configs (site, webhook_secret) VALUES (?, ?)",
			site, secret,
		)
		if err != nil {
			return err
		}
		id, _ = result.LastInsertId()
	} else {
		_, err := tx.Exec(
			"UPDATE webhook_configs SET webhook_secret = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
			secret, id,
		)
		if err != nil {
			return err
		}
	}

	if _, err := tx.Exec("DELETE FROM webhook_allowed_repos WHERE webhook_id = ?", id); err != nil {
		return err
	}

	for _, repo := range repos {
		if repo == "" {
			continue
		}
		_, err := tx.Exec(
			"INSERT INTO webhook_allowed_repos (webhook_id, repository_url) VALUES (?, ?)",
			id, strings.TrimSpace(strings.ToLower(repo)),
		)
		if err != nil {
			return err
		}
	}

	if _, err := tx.Exec("DELETE FROM webhook_allowed_refs WHERE webhook_id = ?", id); err != nil {
		return err
	}

	for _, pattern := range refPatterns {
		if pattern == "" {
			continue
		}
		_, err := tx.Exec(
			"INSERT INTO webhook_allowed_refs (webhook_id, ref_pattern) VALUES (?, ?)",
			id, strings.TrimSpace(pattern),
		)
		if err != nil {
			return err
		}
	}

	return tx.Commit()
}

// GetWebhookConfig retrieves the webhook configuration for a site
func (wcs *WebhookConfigStore) GetWebhookConfig(site string) (*GitWebhookConfig, error) {
	wcs.mu.RLock()
	defer wcs.mu.RUnlock()

	var id int64
	var secret string
	var enabledAt time.Time

	err := wcs.db.QueryRow(
		"SELECT id, webhook_secret, created_at FROM webhook_configs WHERE site = ? AND enabled = 1",
		site,
	).Scan(&id, &secret, &enabledAt)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}

	config := &GitWebhookConfig{
		Site:          site,
		WebhookSecret: secret,
		EnabledAt:     enabledAt,
		Repositories:  []string{},
		AllowedRefs:   []string{},
	}

	rows, err := wcs.db.Query(
		"SELECT repository_url FROM webhook_allowed_repos WHERE webhook_id = ? ORDER BY repository_url",
		id,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var repo string
		if err := rows.Scan(&repo); err != nil {
			return nil, err
		}
		config.Repositories = append(config.Repositories, repo)
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}

	rows, err = wcs.db.Query(
		"SELECT ref_pattern FROM webhook_allowed_refs WHERE webhook_id = ? ORDER BY ref_pattern",
		id,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var pattern string
		if err := rows.Scan(&pattern); err != nil {
			return nil, err
		}
		config.AllowedRefs = append(config.AllowedRefs, pattern)
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}

	return config, nil
}

// DisableWebhookConfig disables webhooks for a site
func (wcs *WebhookConfigStore) DisableWebhookConfig(site string) error {
	wcs.mu.Lock()
	defer wcs.mu.Unlock()

	_, err := wcs.db.Exec(
		"UPDATE webhook_configs SET enabled = 0, updated_at = CURRENT_TIMESTAMP WHERE site = ?",
		site,
	)
	return err
}
