package setup

import (
	"bufio"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
	"unicode"

	"golang.org/x/crypto/bcrypt"
)

// WizardConfig holds settings generated by the first-run wizard
type WizardConfig struct {
	AdminUsername    string
	AdminPassword    string
	SessionSecret    string
	TLSCert          string
	TLSKey           string
	Listen           string
	WebRoot          string
	BackupRoot       string
	Production       bool
}

// Wizard guides users through initial setup
type Wizard struct {
	in  io.Reader
	out io.Writer
}

// NewWizard creates a new setup wizard
func NewWizard(in io.Reader, out io.Writer) *Wizard {
	return &Wizard{in: in, out: out}
}

// Run executes the interactive setup wizard
func (w *Wizard) Run() (WizardConfig, error) {
	cfg := WizardConfig{
		Listen:  ":8080",
		WebRoot: "data/www",
		BackupRoot: "data/backups",
	}

	w.writeLine("🎯 StePanel First-Run Configuration Wizard")
	w.writeLine("")
	w.writeLine("This wizard will guide you through essential setup steps.")
	w.writeLine("")

	// Deployment mode
	mode := w.ask("Is this a production deployment? (yes/no)")
	cfg.Production = strings.ToLower(mode) == "yes" || strings.ToLower(mode) == "y"

	if cfg.Production {
		w.writeLine("")
		w.writeLine("⚠️  Production Mode Enabled")
		w.writeLine("   - HTTPS will be required")
		w.writeLine("   - Strict security validations active")
		w.writeLine("   - Backups must be encrypted")
	}

	// Admin username
	w.writeLine("")
	w.writeLine("🔐 Administrator Account")
	for {
		username := w.ask("Admin username (or press Enter for 'admin')")
		if username == "" {
			username = "admin"
		}
		if len(username) < 2 || len(username) > 32 || !isValidUsername(username) {
			w.writeLine("   ⚠️  Username must be 2-32 characters, alphanumeric + underscore")
			continue
		}
		cfg.AdminUsername = username
		break
	}

	// Admin password
	for {
		password := w.ask("Admin password (min 12 characters)")
		if len(password) < 12 {
			w.writeLine("   ⚠️  Password must be at least 12 characters")
			continue
		}
		if !hasComplexity(password) {
			w.writeLine("   ⚠️  Password should include uppercase, lowercase, numbers, and symbols")
			w.ask("Proceed anyway? (yes/no)")
			if strings.ToLower(w.ask("")) == "yes" {
				cfg.AdminPassword = password
				break
			}
			continue
		}
		cfg.AdminPassword = password
		break
	}

	// Generate secrets
	w.writeLine("")
	w.writeLine("🔑 Generating security secrets...")
	secret, err := generateSecret(32)
	if err != nil {
		return cfg, fmt.Errorf("failed to generate session secret: %w", err)
	}
	cfg.SessionSecret = secret

	// Network configuration
	if cfg.Production {
		w.writeLine("")
		w.writeLine("🌐 Network Configuration")
		listen := w.ask("Listen address (default: 127.0.0.1:8080)")
		if listen != "" {
			cfg.Listen = listen
		}

		cert := w.ask("Path to TLS certificate")
		if cert == "" {
			w.writeLine("   ℹ️  TLS certificate required for production")
			return cfg, errors.New("TLS certificate path required")
		}
		cfg.TLSCert = cert

		key := w.ask("Path to TLS key")
		if key == "" {
			w.writeLine("   ℹ️  TLS key required for production")
			return cfg, errors.New("TLS key path required")
		}
		cfg.TLSKey = key
	}

	// Storage paths
	w.writeLine("")
	w.writeLine("💾 Storage Configuration")
	webroot := w.ask("Web root directory (default: data/www)")
	if webroot != "" {
		cfg.WebRoot = webroot
	}

	backuproot := w.ask("Backup directory (default: data/backups)")
	if backuproot != "" {
		cfg.BackupRoot = backuproot
	}

	// Summary
	w.writeLine("")
	w.writeLine("✅ Configuration Summary")
	w.writeLine("")
	w.writeLine("Save these environment variables to your .env file:")
	w.writeLine("")
	w.writeLine(fmt.Sprintf("STEPANEL_ADMIN_USERNAME=%s", cfg.AdminUsername))
	w.writeLine("STEPANEL_ADMIN_PASSWORD_HASH=<bcrypt-hash>")
	w.writeLine(fmt.Sprintf("STEPANEL_SESSION_SECRET=%s", cfg.SessionSecret))
	if cfg.Production {
		w.writeLine(fmt.Sprintf("STEPANEL_TLS_CERT_FILE=%s", cfg.TLSCert))
		w.writeLine(fmt.Sprintf("STEPANEL_TLS_KEY_FILE=%s", cfg.TLSKey))
		w.writeLine(fmt.Sprintf("STEPANEL_LISTEN=%s", cfg.Listen))
		w.writeLine("STEPANEL_PRODUCTION=true")
	}
	w.writeLine(fmt.Sprintf("STEPANEL_WEB_ROOT=%s", cfg.WebRoot))
	w.writeLine(fmt.Sprintf("STEPANEL_BACKUP_ROOT=%s", cfg.BackupRoot))
	w.writeLine("")

	// Generate password hash
	w.writeLine("🔐 Hashing password...")
	hash, err := bcrypt.GenerateFromPassword([]byte(cfg.AdminPassword), bcrypt.DefaultCost)
	if err != nil {
		return cfg, fmt.Errorf("failed to hash password: %w", err)
	}
	w.writeLine(fmt.Sprintf("STEPANEL_ADMIN_PASSWORD_HASH=%s", string(hash)))
	w.writeLine("")

	w.writeLine("✨ Setup complete! Start the server with your configured environment.")
	w.writeLine("")

	return cfg, nil
}

func (w *Wizard) ask(prompt string) string {
	fmt.Fprintf(w.out, "%s: ", prompt)
	scanner := bufio.NewScanner(w.in)
	if scanner.Scan() {
		return strings.TrimSpace(scanner.Text())
	}
	return ""
}

func (w *Wizard) writeLine(msg string) {
	fmt.Fprintln(w.out, msg)
}

func isValidUsername(s string) bool {
	for _, r := range s {
		if !isLetter(r) && !isDigit(r) && r != '_' {
			return false
		}
	}
	return true
}

func isLetter(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
}

func isDigit(r rune) bool {
	return r >= '0' && r <= '9'
}

func hasComplexity(s string) bool {
	hasUpper := false
	hasLower := false
	hasDigit := false
	hasSymbol := false

	for _, r := range s {
		if unicode.IsUpper(r) {
			hasUpper = true
		} else if unicode.IsLower(r) {
			hasLower = true
		} else if unicode.IsDigit(r) {
			hasDigit = true
		} else if !unicode.IsSpace(r) {
			hasSymbol = true
		}
	}

	return hasUpper && hasLower && hasDigit && hasSymbol
}

func generateSecret(length int) (string, error) {
	bytes := make([]byte, length)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(bytes), nil
}

// ValidateEnvironment checks that critical configuration is present
func ValidateEnvironment() error {
	required := []string{
		"STEPANEL_ADMIN_PASSWORD_HASH",
		"STEPANEL_SESSION_SECRET",
	}

	missing := []string{}
	for _, env := range required {
		if os.Getenv(env) == "" {
			missing = append(missing, env)
		}
	}

	if len(missing) > 0 {
		return fmt.Errorf("missing required environment variables: %v", missing)
	}

	return nil
}
